apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
        server {
            listen 80;
            server_name onetimesecret.rafaelsraposo.cloudns.be;

            location / {
                return 301 https://$host$request_uri;
            }
        }

        server {
            listen 443 ssl;
            server_name onetimesecret.rafaelsraposo.cloudns.be;
            ssl_certificate /etc/ssl/certs/tls.crt;
            ssl_certificate_key /etc/ssl/certs/tls.key;
    
            location / {
                proxy_pass http://secret-service.default.svc.cluster.local:7143;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }

        server {
            listen 80;
            server_name plik.rafaelsraposo.cloudns.be;

            location / {
                return 301 https://$host$request_uri;
            }
        }

        server {
            listen 443 ssl;
            server_name plik.rafaelsraposo.cloudns.be;
    
            ssl_certificate /etc/ssl/certs/tls.crt;
            ssl_certificate_key /etc/ssl/certs/tls.key;
    
            location / {
                proxy_pass http://plik-service.default.svc.cluster.local:8080;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }

        server {
            listen 80;
            server_name wikijs.rafaelsraposo.cloudns.be;

            location / {
                return 301 https://$host$request_uri;
            }
        }
    
        server {
            listen 443 ssl;
            server_name wikijs.rafaelsraposo.cloudns.be;
            ssl_certificate /etc/ssl/certs/tls.crt;
            ssl_certificate_key /etc/ssl/certs/tls.key;

            location / {
                proxy_pass http://wiki-service.default.svc.cluster.local:3000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }

        server {
            listen 80;
            server_name cert.rafaelsraposo.cloudns.be;

            location / {
                rewrite ^/(.*)$ https://$server_name/$1 permanent;
            }
        }

        server {
            listen 443 ssl;
            server_name cert.rafaelsraposo.cloudns.be;

            ssl_certificate /etc/ssl/certs/tls.crt;
            ssl_certificate_key /etc/ssl/certs/tls.key;

            location / {
                proxy_pass https://ejbca-service.default.svc.cluster.local:8443;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
    stream {
      server {
         listen 5432;
         proxy_pass postgres-service.default.svc.cluster.local:5432;
       }
    }