apiVersion: apps/v1
kind: Deployment
metadata:
  name: plik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plik
  template:
    metadata:
      labels:
        app: plik
    spec:
      containers:
        - name: plik
          image: rootgg/plik:latest
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: plik_user
            - name: DB_PASS
              value: plik_password
            - name: DB_NAME
              value: plik
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: plik
spec:
  selector:
    app: plik
  ports:
    - protocol: TCP
      port: 8080