# onetime-secret-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onetime-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onetime-secret
  template:
    metadata:
      labels:
        app: onetime-secret
    spec:
      containers:
        #      - name: pre-init-container
        #        image: ruby:2.7
        #        command: ["/bin/sh", "-c"]
        #        args:
        #        - gem install syslog base64
        #        volumeMounts:
        #        - name: shared-volume
        #          mountPath: /gems
        - name: onetime-secret
          image: dismantl/onetimesecret:latest
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: onetime_user
            - name: DB_PASS
              value: onetime_password
            - name: DB_NAME
              value: onetime
          ports:
            - containerPort: 7143
          volumeMounts:
            - name: shared-volume
              mountPath: /gems
      volumes:
        - name: shared-volume
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: onetime-secret
spec:
  selector:
    app: onetime-secret
  ports:
    - protocol: TCP
      port: 7143
      targetPort: 7143