apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki
  template:
    metadata:
      labels:
        app: wiki
    spec:
      containers:
      - name: wiki
        image: linuxserver/wikijs:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: wiki-service
spec:
  selector:
    app: wiki
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP


